---
- hosts: 172.31.41.69
  become: yes
  tasks:
  - name: i want to copy static files into ansible nodes  side
    copy:
         src: staticfile.html
         dest: /var/www/html/index.html
    notify: restartwebserver


  - name: i want to copy dynamic file inot ansible nodes  side
    template:
        src: dynamicfile.j2
        dest: /var/www/html/index.html
    notify: restartwebserver


  handlers: 
  - name: restartwebserver
    service: 
       name: apache2
       state: restarted