---
- name: copy template user xml file into nodes
  template: 
        scr: templates/tomuser.j2
        dest: /opt/tomcat/conf/tomcat-users.xml 

- name: copy tomcat context xml file into nodes
  template:
        scr: templates/tomcontext.j2
        dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: copy tomcat host context xml file into nodes
  template:
        scr: templates/tomhostcontext.j2
        dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml