---
# tasks file for mywebrole
 - name: install webserver ubuntu
   apt:
     name: apache2
     state: present
   notify: restartwebserver 
   when: ansible_os_family == "Debian"

 - name: install webserver in redhat 
   yum:
     name: httpd
     state: present
   notify: restarterbserver redhat
   when: ansible_os_family == "RedHat"